server:
  port: 8080
spring:
  application:
    name: EasyFlow
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks
  database:
    schema-update: true
springdoc:
  packages-to-scan: com.easyflow.creditapproval.controller
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs